### ISSUE TITLE
Not an issue, but

### ISSUE THREAD

**Issue by sukoshi1507** [WerWolv/EdiZon_ConfigsAndScripts#13]
There is another project on github which has a lot of mods for BOTW, maybe this can be ported for Edizon ?

https://github.com/marcrobledo/savegame-editors/blob/master/zelda-botw/zelda-botw.js

**Comment by ValliantStorme** [comment]
I'm sure, with enough time and enough work, Edizon could achieve feature parity with MarcroBledo's online save editor.
