### ISSUE TITLE
Not exactly an issue re: Xenoblade config

### ISSUE THREAD

**Issue by jacubbear** [WerWolv/EdiZon_ConfigsAndScripts#31]
Hi not very familiar with github so i have no idea how pull requests work, but if you change the max value in the xenoblade config on the "Ether Crystals" from 99 to 99999, it makes editing that actually useful, there's nothing you can do with 99 crystals. Tested the change with my save. Thanks!

**Comment by WerWolv98** [comment]
Fork this repo, make your changes to the config on there and then press on the "Make pull request" button. I can merge it afterwards if it works
