### ISSUE TITLE
zlib support for Xenoblade 2 DLC: Torna the Golden Country

### ISSUE THREAD

**Issue by x43x61x69** [WerWolv/EdiZon_ConfigsAndScripts#39]
[Someone on gbatemp](https://gbatemp.net/threads/xc2savenetthingy-a-xenoblade-chronicles-2-save-editor.512217/page-23#post-8302462) found out that the save of Torna was compressed with zlib.

Is it possible to have a zlib script?

**Comment by WerWolv98** [comment]
You can definitely build one yourself! There's a pure lua implementation of zlib here: https://github.com/zerkman/zzlib
With this it shouldn't be too hard anymore to build an EdiZon script from it
